name: Bug Report
description: Report a bug or an error
title: "BUG: "
labels:
  - "bug"
  - "triage"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for spending time filling this form. We appreciate Your help!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: Specify the way We can contact You if more info is needed!
      placeholder: "ex. <John Doe> email@example.com"
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Tell us what went wrong and what did You expect to happen?
      placeholder: Describe the problem here.
      value: "Some weird stuff happened to me..."
    validations:
      required: true
  - type: input
    id: mc-software
    attributes:
      label: Minecraft Software
      description: Provide us with version string of minecraft server You're running
      placeholder: Paper 1.20.1 (git-dead255beef)
    validations:
      required: true
  - type: dropdown
    id: release-tag
    attributes:
      label: Paperwork Version
      description: What version of Paperwork You're using?
      multiple: true
      options:
        - 0.0 (beta)
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: sh
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/DrupalDoesNotExists/Paperwork/blob/master/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
